name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto si deseas desplegar desde otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Cambia al número de versión que usa tu proyecto

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the Popup Provider
        run: pnpm run build:package

      - name: Build the Application
        run: pnpm run build:web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
